# Generated by Django 5.1.1 on 2024-10-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField()),
                ('category_product_count', models.IntegerField(default=0)),
            ],
        ),
    ]
