# Generated by Django 5.1.1 on 2024-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
