# Generated by Django 5.1.1 on 2024-10-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_customer_id', models.IntegerField()),
                ('order_address_id', models.IntegerField()),
            ],
        ),
    ]
