# Generated by Django 5.1.1 on 2024-10-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address_id',
            field=models.CharField(max_length=100),
        ),
    ]
