# Generated by Django 5.1.1 on 2024-10-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_address_id',
            new_name='order_address',
        ),
    ]
