# Generated by Django 5.1.1 on 2024-10-05 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_category_id_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_category_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
