# Generated by Django 5.1.1 on 2024-10-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_order_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_customer_id',
            new_name='order_customer',
        ),
    ]
