# Generated by Django 5.1.1 on 2024-10-05 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_order_customer_id_order_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_customer',
            field=models.ForeignKey(db_column='order_customer_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_customer',
            new_name='order_customer_id',
        ),
    ]
